services:
  frontend:
    build: ./frontend
    container_name: university_frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always

  api:
    build: .
    container_name: university_api
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  castlemock:
    image: castlemock/castlemock
    container_name: castlemock
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./castlemock_data_persistent:/root/.castlemock
    restart: unless-stopped
