<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<restMockResponse>
    <id>zBPI9N</id>
    <name>Returns success message: Cloudy</name>
    <body>{
  "city": "Berlin",
  "temperature": 18,
  "condition": "Cloudy"
}
</body>
    <methodId>ME539S</methodId>
    <status>ENABLED</status>
    <httpStatusCode>200</httpStatusCode>
    <usingExpressions>false</usingExpressions>
    <httpHeaders/>
    <contentEncodings/>
    <parameterQueries/>
    <xpathExpressions/>
    <jsonPathExpressions/>
    <headerQueries/>
</restMockResponse>
